# Generated by Django 5.0.3 on 2024-04-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='vendor_name',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_amount_incl_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_currency',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchase_order',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ship_to_city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ship_to_country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ship_to_state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ship_to_street1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ship_to_street2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ship_to_zip',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier_address_street1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier_address_street2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier_city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier_country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier_state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier_zip',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
